# Generated by Django 4.2.5 on 2023-09-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprint',
            name='bolak_balik',
            field=models.BooleanField(default=False),
        ),
    ]
