# Generated by Django 4.2.5 on 2023-09-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fileprint_printed_alter_fileprint_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprint',
            name='tipe_print',
            field=models.CharField(blank=True, choices=[('1-4', '1 lembar 4 halaman'), ('1-2', '1 lembar 2 halaman'), ('1-1', '1 lembar 1 halaman')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fileprint',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
