# Generated by Django 4.2.5 on 2023-09-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fileprint_tipe_print_alter_fileprint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprint',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
