# Generated by Django 4.2.5 on 2023-09-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_fileprint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprint',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
