# Generated by Django 4.2.5 on 2023-09-16 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_is_email_verified_remove_user_nim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileprint',
            name='taken_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
